test = {   'name': 'q3_3_1',
    'points': 2,
    'suites': [   {   'cases': [   {   'code': '>>> int(round(duration_std))\n',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> int(round(wait_std))\n',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
